services:
  db:
    image: postgres:15
    container_name: vidaplus-sghss
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senhadb
      POSTGRES_DB: vidaplus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
